spring:
  application:
    name: api-gateway-2
        
server:
  port: 8082

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      default-zone: http://localhost:8761/eureka/
