#spring.application.name=student
#server.port=8090

spring:
  application:
    name: student-service

server:
  port: 8090

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    server-url:
      default-zone: http://localhost:8761/eureka/

