resource_types:
- name: concourse-git-semver-tag
  type: docker-image
  source:
    repository: laurentverbruggen/concourse-git-semver-tag-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

- name: artifactory
  type: docker-image
  source:
    repository: pivotalservices/artifactory-resource

resources:
  - name: royzding
    type: git
    source:
      uri: https://github.com/royzding/royzding.git
      branch: master
jobs:
- name: java-build
  plan:
  - get: royzding
    trigger: true
  - task: run-build
    file: royzding/SB-Eureka-Server/ci/build.yml

