# Declare Concourse resources to use as IN/OUT 
resources:  
  # 'code' resource is a GIT resource used to checkout source-code
  - name: code  
    type: git  
    source:  
      uri: https://gitlab.gologic.ca/gologic-technos/continuous-deployment.git
      branch: master

jobs:  
  # First job: Package Application as a JAR and Upload to S3 Bucket for storage
  - name: Build  
    plan:  
    # Check for new commit (trigger=true), 'code' refers to GIT resource
    - get: code  
      trigger: true  
    # Package and copy application to output 'build' folder
    - task: compile  
      config:
        # Use a docker image with Maven to build application
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: maven
        # 'code' folder contains checkout code
        inputs:
          - name: code
        # 'build' folder is used to store file for next PUT step after RUN step
        outputs: 
          - name: build
        caches:
          - path: code/.m2
        # RUN step allows inline command and FILE step allows use of external task file
        run:
          path: sh
          args:
          - -c
          - |
            mvn -f code/pom.xml package -Dmaven.repo.local=code/.m2
            cp code/target/demo-1.0.jar build/demo.jar